name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }

      - name: Build
        run: |
          make build-${{ matrix.goos }}/${{ matrix.goarch }}

      - name: Package
        run: |
          make package-${{ matrix.goos }}/${{ matrix.goarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: litepost-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            dist/litepost-${{ matrix.goos }}-${{ matrix.goarch }}.zip
            dist/litepost-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          if-no-files-found: ignore

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/litepost-*.zip
            dist/**/litepost-*.tar.gz
